[package]
name = "rns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font-kit = "0.11.0"
minifb = "0.24.0"
raqote = "0.8.2"
tokio = "1.28.2"
